### ISSUE TITLE
There are 'compile' instructions but no 'run server' instructions

### ISSUE THREAD

**Issue by danbri** [cdglabs/Shadershop#10]
I was expecting to be able to do something like 'node app.js' to run a local http server to see this running. Not being a node.js person, I've failed to find the magic command. Could you spell out exactly what is needed, even if it seems painfully obvious? Will any HTTP server do, or is Node needed?

**Comment by electronicwhisper** [comment]
Done :sparkles:

**Comment by danbri** [comment]
And I was over-thinking it :) Thanks, glad I asked. Hopefully it'll help someone else too...
