### ISSUE TITLE
Not obvious how to delete my various test functions

### ISSUE THREAD

**Issue by danbri** [cdglabs/Shadershop#11]
The app retains state for a long time. I found the 'sinewaves' key under Local Storage (OSX Chrome) and managed to reset it there but I don't see how to do that through the main UI. Cmd/option/ctrl/etc-click on the entries in lower-left panel doesn't help, and the backspace key exits the page entirely. Assuming I'm missing something obvious again...

**Comment by electronicwhisper** [comment]
Ctrl+R to reset. I added this to the readme as well.

**Comment by danbri** [comment]
Forgot this - came back here and remembered it :)
