### ISSUE TITLE
No gradation in colormap

### ISSUE THREAD

**Issue by JobJob** [cdglabs/Shadershop#2]
This looks great, well done. 

Not sure if I'm missing something but the 2d colormap view seems to only show blue or white for me - corresponding to values less than or greater then zero, unlike in the demo video where there is a smooth transition from white through black to blue. See attached. This is on OSX 10.9.5 (with a GPU) Firefox 33.1.1 and Chrome 39.

![shadershop sine color map bug](https://cloud.githubusercontent.com/assets/854183/5261145/144e8c5a-7a1f-11e4-8fcb-2dc338e1c58f.png)

**Comment by bbrks** [comment]
Same issue on OS X 10.10.1 on the following browsers:
- Chrome 40.0.2214.10 beta (64-bit)
- Firefox Developer Edition 35.0a2 (2014-11-15)
- Safari Version 8.0 (10600.1.25.1)

Seems unlikely that it's a browser specific issue.

**Comment by JobJob** [comment]
Nice, that fixes it for me :+1:

**Comment by electronicwhisper** [comment]
Fixed by @bbrks 's PR. Thanks for reporting @JobJob !
